version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    env_file: ./server-nest/.env
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}'