version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    environment:
      - 'PORT=${PORT}'
    ports:
      - '${PORT}:${PORT}'